# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc978bebfd28ceafcc6364b473b38e183f65a039b3811bc46d6ea10f6bb0936bad0f7e0c061c19d5288390e4b80ed9908f532d689539b2a550235b5f65b5d23c

test:
  secret_key_base: 8cb34d115d3f8a4050459027c2e05728ce8e48c3d601027a79be8eb9ef90b9645855f7433b7d3f4d2d7a06e386065aded4b7ec492f098924fd27bd8d822ab273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
